/********************************************************************************
** Form generated from reading UI file 'chatwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CHATWINDOW_H
#define UI_CHATWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ChatWindow
{
public:
    QGridLayout *gridLayout;
    QPushButton *connectButton;
    QListView *chatView;
    QLineEdit *messageEdit;
    QPushButton *sendButton;

    void setupUi(QWidget *ChatWindow)
    {
        if (ChatWindow->objectName().isEmpty())
            ChatWindow->setObjectName(QStringLiteral("ChatWindow"));
        ChatWindow->resize(400, 300);
        ChatWindow->setStyleSheet(QLatin1String("/*-----QWidget-----*/\n"
"\n"
"QWidget\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(27, 39, 50, 255),stop:1 rgba(47, 53, 74, 255));\n"
"\n"
"	color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"\n"
"QLabel\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #c2c7d5;\n"
"\n"
"	font-size: 13px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 11px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::pressed\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 207, 1"
                        "79, 255),stop:1 rgba(70, 255, 230, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 10px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox::indicator\n"
"\n"
"{\n"
"\n"
"    color: #b1b1b1;\n"
"\n"
"    background-color: #323232;\n"
"\n"
"    border: 1px solid darkgray;\n"
"\n"
"    width: 12px;\n"
"\n"
"    height: 12px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"\n"
"{\n"
"\n"
"    image:url(\"./ressources/check.png\");\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border: 1px solid #607cff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover"
                        "\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #08b099;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"\n"
"{\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"    border: 1px solid #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"\n"
"QLineEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #c2c7d5;\n"
"\n"
"	color: #000;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"	padding: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"\n"
"QListView\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(50, 61, 80, 255),stop:1 rgba(44, 49, 69, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 12px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: 1px solid #191919;\n"
"\n"
"	show-decoration-selec"
                        "ted: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding: 5px;\n"
"\n"
"	border-radius: 0px;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"	height: 42px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QListView::item:selected\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected\n"
"\n"
"{\n"
"\n"
"	color:white;\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected:hover\n"
"\n"
"{\n"
"\n"
"	color: #bbbcba;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"\n"
"QTreeView \n"
"\n"
"{\n"
"\n"
"	background-color: #232939;\n"
"\n"
"	show-decoration-selected: 0;\n"
"\n"
""
                        "	color: #c2c8d7;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item \n"
"\n"
"{\n"
"\n"
"	border-top-color: transparent;\n"
"\n"
"	border-bottom-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:hover \n"
"\n"
"{\n"
"\n"
"	background-color: #606060;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected:active\n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"\n"
"{\n"
"\n"
"	image: url(://tree-closed.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"\n"
"{\n"
"\n"
"	image: url(:"
                        "//tree-open.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"\n"
"QTableView\n"
"\n"
"{\n"
"\n"
"    background-color: #232939;\n"
"\n"
"	border: 1px solid gray;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"    gridline-color: #232939;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #242526;\n"
"\n"
"    border: 1px solid #32414B;\n"
"\n"
"    color: #656565;\n"
"\n"
"    gridline-color: #656565;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:hover \n"
"\n"
"{\n"
"\n"
"    background-color: #606060;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"    color: #F0F0F0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #1a1b1c;\n"
"\n"
"    border:"
                        " 2px solid #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"\n"
"{\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"\n"
"{\n"
"\n"
"	color: #fff;\n"
"\n"
"	border-top: 0px;\n"
"\n"
"	border-bottom: 1px solid gray;\n"
"\n"
"	border-right: 1px solid gray;\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    margin-top:1px;\n"
"\n"
"	margin-bottom:1px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"\n"
"{\n"
"\n"
"    color: #fff;\n"
"\n"
"    background-color: #0ab19a;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"\n"
"{\n"
"\n"
"    color: #656565;\n"
"\n"
"    background-color: #525251;\n"
"\n"
""
                        "\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"\n"
"QHeaderView::section::vertical::only-one\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"\n"
"QHeaderView::section::horizontal::only-one\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"\n"
"QScrollBar:horizontal \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    height: 8px;\n"
"\n"
"    margin: 0px;\n"
"\n"
"    padding: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
""
                        "	min-width: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"\n"
"QScrollBar::sub-line:horizontal,\n"
"\n"
"QScrollBar::add-page:horizontal, \n"
"\n"
"QScrollBar::sub-page:horizontal \n"
"\n"
"{\n"
"\n"
"    width: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    width: 8px;\n"
"\n"
"    margin: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
"	min-height: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"\n"
"QScrollBar::add-page:vertical, \n"
"\n"
"QScrollBar::sub-page:vertical \n"
"\n"
"{\n"
"\n"
"    height: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
""
                        "QGroupBox  {\n"
"\n"
"    border: 1px solid gray;\n"
"\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    margin-top: 27px;\n"
"\n"
"    font-size: 14px;\n"
"\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox::title  {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    subcontrol-position: top center;\n"
"\n"
"    padding: 5px 8000px 5px 8000px;\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    background: white;\n"
"\n"
"    selection-background-color: darkgray;\n"
"\n"
"}\n"
"\n"
"QComboBox {\n"
"\n"
"    border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding:"
                        " 0 8px;\n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:editable {\n"
"\n"
"    background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"\n"
"     background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"    padding-top: 3px;\n"
"\n"
"    padding-left: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    subcontrol-position: top right;\n"
"\n"
"    width: 15px;\n"
"\n"
"\n"
"\n"
"    border-left-width: 1px;\n"
"\n"
"    border-left-color: darkgray;\n"
""
                        "\n"
"    border-left-style: solid; /* just a single line */\n"
"\n"
"    border-top-right-radius: 10px; /* same radius as the QComboBox */\n"
"\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"\n"
"    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"    top: 1px;\n"
"\n"
"    left: 1px;\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    selection-background-color: lightgray;\n"
"\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"\n"
"    border-top: 2px solid #C2C7CB;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"\n"
"    left: 5px; /* move to the right by 5px */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar::tab {\n"
"\n"
"    background: qlineargradient(x1"
                        ": 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"\n"
"    border-top-left-radius: 4px;\n"
"\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    min-width: 8ex;\n"
"\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    border-color:qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"    border-bottom-c"
                        "olor: #C2C7CB; /* same as pane color */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected {\n"
"\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    /* expand/overlap to the left and right by 4px */\n"
"\n"
"    margin-left: -4px;\n"
"\n"
"    margin-right: -4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:first:selected {\n"
"\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:last:selected {\n"
"\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:only-one {\n"
"\n"
"    margin: 0; /* if there is only one tab, we don't want overlapping margins */\n"
"\n"
"}\n"
"\n"
"QRadioButton{\n"
"\n"
"\n"
"\n"
"	color:white;\n"
"\n"
"	font:solid;\n"
"\n"
"}\n"
"\n"
"QDateEdit\n"
"\n"
"{\n"
"\n"
"    backgrou"
                        "nd-color: white;\n"
"\n"
"	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"\n"
"    width:50px;\n"
"\n"
"    height:15px;\n"
"\n"
"    subcontrol-position: right top;\n"
"\n"
"    subcontrol-origin:margin;\n"
"\n"
"    background-color: white;\n"
"\n"
"   	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"   spacing: 5px; \n"
"\n"
"}"));
        gridLayout = new QGridLayout(ChatWindow);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        connectButton = new QPushButton(ChatWindow);
        connectButton->setObjectName(QStringLiteral("connectButton"));

        gridLayout->addWidget(connectButton, 0, 0, 1, 2);

        chatView = new QListView(ChatWindow);
        chatView->setObjectName(QStringLiteral("chatView"));
        chatView->setEnabled(false);
        chatView->setEditTriggers(QAbstractItemView::NoEditTriggers);

        gridLayout->addWidget(chatView, 1, 0, 1, 2);

        messageEdit = new QLineEdit(ChatWindow);
        messageEdit->setObjectName(QStringLiteral("messageEdit"));
        messageEdit->setEnabled(false);

        gridLayout->addWidget(messageEdit, 2, 0, 1, 1);

        sendButton = new QPushButton(ChatWindow);
        sendButton->setObjectName(QStringLiteral("sendButton"));
        sendButton->setEnabled(false);

        gridLayout->addWidget(sendButton, 2, 1, 1, 1);


        retranslateUi(ChatWindow);

        sendButton->setDefault(true);


        QMetaObject::connectSlotsByName(ChatWindow);
    } // setupUi

    void retranslateUi(QWidget *ChatWindow)
    {
        ChatWindow->setWindowTitle(QApplication::translate("ChatWindow", "Qt Simple Chat Client", Q_NULLPTR));
        connectButton->setText(QApplication::translate("ChatWindow", "Connect", Q_NULLPTR));
        sendButton->setText(QApplication::translate("ChatWindow", "Send", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ChatWindow: public Ui_ChatWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CHATWINDOW_H
