/********************************************************************************
** Form generated from reading UI file 'employee.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EMPLOYEE_H
#define UI_EMPLOYEE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Employee
{
public:
    QTabWidget *tab_produits_2;
    QWidget *tab;
    QGroupBox *groupBox;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_6;
    QHBoxLayout *horizontalLayout_2;
    QVBoxLayout *verticalLayout_2;
    QLabel *label;
    QLabel *label_3;
    QLabel *label_2;
    QLabel *label_4;
    QLabel *label_5;
    QVBoxLayout *verticalLayout;
    QLineEdit *line_ID;
    QLineEdit *line_nom;
    QLineEdit *line_prenom;
    QLineEdit *line_salaire;
    QComboBox *combo_type;
    QHBoxLayout *horizontalLayout_4;
    QPushButton *btn_ajout;
    QPushButton *btn_modif;
    QPushButton *btn_sup;
    QGroupBox *groupBox_2;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout_3;
    QVBoxLayout *verticalLayout_3;
    QPushButton *tout_afficher_emp;
    QPushButton *pdf_emp;
    QVBoxLayout *verticalLayout_5;
    QVBoxLayout *verticalLayout_4;
    QRadioButton *tri_salaire_emp;
    QRadioButton *tri_type_emp;
    QRadioButton *tri_nom_emp;
    QPushButton *quitter_emp;
    QPushButton *btn_chat_emp;
    QWidget *layoutWidget2;
    QVBoxLayout *verticalLayout_7;
    QHBoxLayout *horizontalLayout;
    QLabel *label_8;
    QLineEdit *line_rech_emp;
    QTableView *tableView;
    QWidget *layoutWidget3;
    QVBoxLayout *verticalLayout_8;
    QHBoxLayout *horizontalLayout_5;
    QLabel *label_6;
    QComboBox *comboBox_modif;
    QHBoxLayout *horizontalLayout_6;
    QLabel *label_7;
    QComboBox *comboBox_rech_emp;
    QLabel *label_info;
    QWidget *tab_produits;
    QWidget *tab_articles;
    QWidget *tab_2;
    QWidget *tab_3;

    void setupUi(QWidget *Employee)
    {
        if (Employee->objectName().isEmpty())
            Employee->setObjectName(QStringLiteral("Employee"));
        Employee->resize(979, 538);
        Employee->setStyleSheet(QLatin1String("/*-----QWidget-----*/\n"
"\n"
"QWidget\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(27, 39, 50, 255),stop:1 rgba(47, 53, 74, 255));\n"
"\n"
"	color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"\n"
"QLabel\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #c2c7d5;\n"
"\n"
"	font-size: 13px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 11px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::pressed\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 207, 1"
                        "79, 255),stop:1 rgba(70, 255, 230, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 10px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox::indicator\n"
"\n"
"{\n"
"\n"
"    color: #b1b1b1;\n"
"\n"
"    background-color: #323232;\n"
"\n"
"    border: 1px solid darkgray;\n"
"\n"
"    width: 12px;\n"
"\n"
"    height: 12px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"\n"
"{\n"
"\n"
"    image:url(\"./ressources/check.png\");\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border: 1px solid #607cff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover"
                        "\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #08b099;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"\n"
"{\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"    border: 1px solid #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"\n"
"QLineEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #c2c7d5;\n"
"\n"
"	color: #000;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"	padding: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"\n"
"QListView\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(50, 61, 80, 255),stop:1 rgba(44, 49, 69, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 12px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: 1px solid #191919;\n"
"\n"
"	show-decoration-selec"
                        "ted: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding: 5px;\n"
"\n"
"	border-radius: 0px;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"	height: 42px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QListView::item:selected\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected\n"
"\n"
"{\n"
"\n"
"	color:white;\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected:hover\n"
"\n"
"{\n"
"\n"
"	color: #bbbcba;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"\n"
"QTreeView \n"
"\n"
"{\n"
"\n"
"	background-color: #232939;\n"
"\n"
"	show-decoration-selected: 0;\n"
"\n"
""
                        "	color: #c2c8d7;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item \n"
"\n"
"{\n"
"\n"
"	border-top-color: transparent;\n"
"\n"
"	border-bottom-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:hover \n"
"\n"
"{\n"
"\n"
"	background-color: #606060;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected:active\n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"\n"
"{\n"
"\n"
"	image: url(://tree-closed.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"\n"
"{\n"
"\n"
"	image: url(:"
                        "//tree-open.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"\n"
"QTableView\n"
"\n"
"{\n"
"\n"
"    background-color: #232939;\n"
"\n"
"	border: 1px solid gray;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"    gridline-color: #232939;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #242526;\n"
"\n"
"    border: 1px solid #32414B;\n"
"\n"
"    color: #656565;\n"
"\n"
"    gridline-color: #656565;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:hover \n"
"\n"
"{\n"
"\n"
"    background-color: #606060;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"    color: #F0F0F0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #1a1b1c;\n"
"\n"
"    border:"
                        " 2px solid #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"\n"
"{\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"\n"
"{\n"
"\n"
"	color: #fff;\n"
"\n"
"	border-top: 0px;\n"
"\n"
"	border-bottom: 1px solid gray;\n"
"\n"
"	border-right: 1px solid gray;\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    margin-top:1px;\n"
"\n"
"	margin-bottom:1px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"\n"
"{\n"
"\n"
"    color: #fff;\n"
"\n"
"    background-color: #0ab19a;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"\n"
"{\n"
"\n"
"    color: #656565;\n"
"\n"
"    background-color: #525251;\n"
"\n"
""
                        "\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"\n"
"QHeaderView::section::vertical::only-one\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"\n"
"QHeaderView::section::horizontal::only-one\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"\n"
"QScrollBar:horizontal \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    height: 8px;\n"
"\n"
"    margin: 0px;\n"
"\n"
"    padding: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
""
                        "	min-width: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"\n"
"QScrollBar::sub-line:horizontal,\n"
"\n"
"QScrollBar::add-page:horizontal, \n"
"\n"
"QScrollBar::sub-page:horizontal \n"
"\n"
"{\n"
"\n"
"    width: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    width: 8px;\n"
"\n"
"    margin: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
"	min-height: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"\n"
"QScrollBar::add-page:vertical, \n"
"\n"
"QScrollBar::sub-page:vertical \n"
"\n"
"{\n"
"\n"
"    height: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
""
                        "QGroupBox  {\n"
"\n"
"    border: 1px solid gray;\n"
"\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    margin-top: 27px;\n"
"\n"
"    font-size: 14px;\n"
"\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox::title  {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    subcontrol-position: top center;\n"
"\n"
"    padding: 5px 8000px 5px 8000px;\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    background: white;\n"
"\n"
"    selection-background-color: darkgray;\n"
"\n"
"}\n"
"\n"
"QComboBox {\n"
"\n"
"    border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding:"
                        " 0 8px;\n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:editable {\n"
"\n"
"    background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"\n"
"     background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"    padding-top: 3px;\n"
"\n"
"    padding-left: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    subcontrol-position: top right;\n"
"\n"
"    width: 15px;\n"
"\n"
"\n"
"\n"
"    border-left-width: 1px;\n"
"\n"
"    border-left-color: darkgray;\n"
""
                        "\n"
"    border-left-style: solid; /* just a single line */\n"
"\n"
"    border-top-right-radius: 10px; /* same radius as the QComboBox */\n"
"\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"\n"
"    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"    top: 1px;\n"
"\n"
"    left: 1px;\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    selection-background-color: lightgray;\n"
"\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"\n"
"    border-top: 2px solid #C2C7CB;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"\n"
"    left: 5px; /* move to the right by 5px */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar::tab {\n"
"\n"
"    background: qlineargradient(x1"
                        ": 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"\n"
"    border-top-left-radius: 4px;\n"
"\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    min-width: 8ex;\n"
"\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    border-color:qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"    border-bottom-c"
                        "olor: #C2C7CB; /* same as pane color */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected {\n"
"\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    /* expand/overlap to the left and right by 4px */\n"
"\n"
"    margin-left: -4px;\n"
"\n"
"    margin-right: -4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:first:selected {\n"
"\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:last:selected {\n"
"\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:only-one {\n"
"\n"
"    margin: 0; /* if there is only one tab, we don't want overlapping margins */\n"
"\n"
"}\n"
"\n"
"QRadioButton{\n"
"\n"
"\n"
"\n"
"	color:white;\n"
"\n"
"	font:solid;\n"
"\n"
"}\n"
"\n"
"QDateEdit\n"
"\n"
"{\n"
"\n"
"    backgrou"
                        "nd-color: white;\n"
"\n"
"	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"\n"
"    width:50px;\n"
"\n"
"    height:15px;\n"
"\n"
"    subcontrol-position: right top;\n"
"\n"
"    subcontrol-origin:margin;\n"
"\n"
"    background-color: white;\n"
"\n"
"   	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"   spacing: 5px; \n"
"\n"
"}"));
        tab_produits_2 = new QTabWidget(Employee);
        tab_produits_2->setObjectName(QStringLiteral("tab_produits_2"));
        tab_produits_2->setGeometry(QRect(10, 10, 941, 521));
        tab_produits_2->setStyleSheet(QLatin1String("/*-----QWidget-----*/\n"
"\n"
"QWidget\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(27, 39, 50, 255),stop:1 rgba(47, 53, 74, 255));\n"
"\n"
"	color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"\n"
"QLabel\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #c2c7d5;\n"
"\n"
"	font-size: 13px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 11px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::pressed\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 207, 1"
                        "79, 255),stop:1 rgba(70, 255, 230, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 10px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox::indicator\n"
"\n"
"{\n"
"\n"
"    color: #b1b1b1;\n"
"\n"
"    background-color: #323232;\n"
"\n"
"    border: 1px solid darkgray;\n"
"\n"
"    width: 12px;\n"
"\n"
"    height: 12px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"\n"
"{\n"
"\n"
"    image:url(\"./ressources/check.png\");\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border: 1px solid #607cff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover"
                        "\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #08b099;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"\n"
"{\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"    border: 1px solid #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"\n"
"QLineEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #c2c7d5;\n"
"\n"
"	color: #000;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: none;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"	padding: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"\n"
"QListView\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(50, 61, 80, 255),stop:1 rgba(44, 49, 69, 255));\n"
"\n"
"	color: #fff;\n"
"\n"
"	font-size: 12px;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: 1px solid #191919;\n"
"\n"
"	show-decoration-selec"
                        "ted: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding: 5px;\n"
"\n"
"	border-radius: 0px;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"	height: 42px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QListView::item:selected\n"
"\n"
"{\n"
"\n"
"	color: #31cecb;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected\n"
"\n"
"{\n"
"\n"
"	color:white;\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QListView::item:!selected:hover\n"
"\n"
"{\n"
"\n"
"	color: #bbbcba;\n"
"\n"
"	background-color: #454e5e;\n"
"\n"
"	border: none;\n"
"\n"
"	padding-left : 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"\n"
"QTreeView \n"
"\n"
"{\n"
"\n"
"	background-color: #232939;\n"
"\n"
"	show-decoration-selected: 0;\n"
"\n"
""
                        "	color: #c2c8d7;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item \n"
"\n"
"{\n"
"\n"
"	border-top-color: transparent;\n"
"\n"
"	border-bottom-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:hover \n"
"\n"
"{\n"
"\n"
"	background-color: #606060;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::item:selected:active\n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"\n"
"{\n"
"\n"
"	image: url(://tree-closed.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"\n"
"{\n"
"\n"
"	image: url(:"
                        "//tree-open.png);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"\n"
"QTableView\n"
"\n"
"{\n"
"\n"
"    background-color: #232939;\n"
"\n"
"	border: 1px solid gray;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"    gridline-color: #232939;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #242526;\n"
"\n"
"    border: 1px solid #32414B;\n"
"\n"
"    color: #656565;\n"
"\n"
"    gridline-color: #656565;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:hover \n"
"\n"
"{\n"
"\n"
"    background-color: #606060;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected \n"
"\n"
"{\n"
"\n"
"	background-color: #0ab19a;\n"
"\n"
"    color: #F0F0F0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #1a1b1c;\n"
"\n"
"    border:"
                        " 2px solid #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"\n"
"{\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"\n"
"{\n"
"\n"
"	color: #fff;\n"
"\n"
"	border-top: 0px;\n"
"\n"
"	border-bottom: 1px solid gray;\n"
"\n"
"	border-right: 1px solid gray;\n"
"\n"
"	background-color: #343a49;\n"
"\n"
"    margin-top:1px;\n"
"\n"
"	margin-bottom:1px;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"\n"
"{\n"
"\n"
"    color: #fff;\n"
"\n"
"    background-color: #0ab19a;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"\n"
"{\n"
"\n"
"    color: #656565;\n"
"\n"
"    background-color: #525251;\n"
"\n"
""
                        "\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"\n"
"QHeaderView::section::vertical::only-one\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"\n"
"{\n"
"\n"
"    border-top: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"\n"
"QHeaderView::section::horizontal::only-one\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"\n"
"{\n"
"\n"
"    border-left: 1px solid #353635;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"\n"
"QScrollBar:horizontal \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    height: 8px;\n"
"\n"
"    margin: 0px;\n"
"\n"
"    padding: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
""
                        "	min-width: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"\n"
"QScrollBar::sub-line:horizontal,\n"
"\n"
"QScrollBar::add-page:horizontal, \n"
"\n"
"QScrollBar::sub-page:horizontal \n"
"\n"
"{\n"
"\n"
"    width: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    width: 8px;\n"
"\n"
"    margin: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"\n"
"{\n"
"\n"
"    border: none;\n"
"\n"
"	min-height: 100px;\n"
"\n"
"    background-color: #56576c;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"\n"
"QScrollBar::add-page:vertical, \n"
"\n"
"QScrollBar::sub-page:vertical \n"
"\n"
"{\n"
"\n"
"    height: 0px;\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
""
                        "QGroupBox  {\n"
"\n"
"    border: 1px solid gray;\n"
"\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    margin-top: 27px;\n"
"\n"
"    font-size: 14px;\n"
"\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox::title  {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    subcontrol-position: top center;\n"
"\n"
"    padding: 5px 8000px 5px 8000px;\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    background: white;\n"
"\n"
"    selection-background-color: darkgray;\n"
"\n"
"}\n"
"\n"
"QComboBox {\n"
"\n"
"    border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding:"
                        " 0 8px;\n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:editable {\n"
"\n"
"    background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"\n"
"     background: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"    padding-top: 3px;\n"
"\n"
"    padding-left: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    subcontrol-position: top right;\n"
"\n"
"    width: 15px;\n"
"\n"
"\n"
"\n"
"    border-left-width: 1px;\n"
"\n"
"    border-left-color: darkgray;\n"
""
                        "\n"
"    border-left-style: solid; /* just a single line */\n"
"\n"
"    border-top-right-radius: 10px; /* same radius as the QComboBox */\n"
"\n"
"    border-bottom-right-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"\n"
"    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"    top: 1px;\n"
"\n"
"    left: 1px;\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"\n"
"    border: 2px solid gray;\n"
"\n"
"    selection-background-color: lightgray;\n"
"\n"
"}\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"\n"
"    border-top: 2px solid #C2C7CB;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"\n"
"    left: 5px; /* move to the right by 5px */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar::tab {\n"
"\n"
"    background: qlineargradient(x1"
                        ": 0, y1: 0, x2: 0, y2: 1,\n"
"\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));;\n"
"\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"\n"
"    border-top-left-radius: 4px;\n"
"\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    min-width: 8ex;\n"
"\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    border-color:qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.511, stop:0 rgba(0, 172, 149, 255),stop:0.995192 rgba(54, 197, 177, 255));\n"
"\n"
"    border-bottom-c"
                        "olor: #C2C7CB; /* same as pane color */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected {\n"
"\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* make use of negative margins for overlapping tabs */\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    /* expand/overlap to the left and right by 4px */\n"
"\n"
"    margin-left: -4px;\n"
"\n"
"    margin-right: -4px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:first:selected {\n"
"\n"
"    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:last:selected {\n"
"\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:only-one {\n"
"\n"
"    margin: 0; /* if there is only one tab, we don't want overlapping margins */\n"
"\n"
"}\n"
"\n"
"QRadioButton{\n"
"\n"
"\n"
"\n"
"	color:white;\n"
"\n"
"	font:solid;\n"
"\n"
"}\n"
"\n"
"QDateEdit\n"
"\n"
"{\n"
"\n"
"    backgrou"
                        "nd-color: white;\n"
"\n"
"	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"\n"
"    width:50px;\n"
"\n"
"    height:15px;\n"
"\n"
"    subcontrol-position: right top;\n"
"\n"
"    subcontrol-origin:margin;\n"
"\n"
"    background-color: white;\n"
"\n"
"   	border: 2px solid grey;\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"    padding: 0 8px;\n"
"\n"
"    spacing: 5px; \n"
"\n"
"    min-width: 6em;\n"
"\n"
"   spacing: 5px; \n"
"\n"
"}\n"
"\n"
""));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(510, 140, 411, 301));
        layoutWidget = new QWidget(groupBox);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 30, 391, 251));
        verticalLayout_6 = new QVBoxLayout(layoutWidget);
        verticalLayout_6->setObjectName(QStringLiteral("verticalLayout_6"));
        verticalLayout_6->setContentsMargins(0, 0, 0, 0);
        horizontalLayout_2 = new QHBoxLayout();
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        verticalLayout_2 = new QVBoxLayout();
        verticalLayout_2->setObjectName(QStringLiteral("verticalLayout_2"));
        label = new QLabel(layoutWidget);
        label->setObjectName(QStringLiteral("label"));

        verticalLayout_2->addWidget(label);

        label_3 = new QLabel(layoutWidget);
        label_3->setObjectName(QStringLiteral("label_3"));

        verticalLayout_2->addWidget(label_3);

        label_2 = new QLabel(layoutWidget);
        label_2->setObjectName(QStringLiteral("label_2"));

        verticalLayout_2->addWidget(label_2);

        label_4 = new QLabel(layoutWidget);
        label_4->setObjectName(QStringLiteral("label_4"));

        verticalLayout_2->addWidget(label_4);

        label_5 = new QLabel(layoutWidget);
        label_5->setObjectName(QStringLiteral("label_5"));

        verticalLayout_2->addWidget(label_5);


        horizontalLayout_2->addLayout(verticalLayout_2);

        verticalLayout = new QVBoxLayout();
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        line_ID = new QLineEdit(layoutWidget);
        line_ID->setObjectName(QStringLiteral("line_ID"));

        verticalLayout->addWidget(line_ID);

        line_nom = new QLineEdit(layoutWidget);
        line_nom->setObjectName(QStringLiteral("line_nom"));

        verticalLayout->addWidget(line_nom);

        line_prenom = new QLineEdit(layoutWidget);
        line_prenom->setObjectName(QStringLiteral("line_prenom"));

        verticalLayout->addWidget(line_prenom);

        line_salaire = new QLineEdit(layoutWidget);
        line_salaire->setObjectName(QStringLiteral("line_salaire"));

        verticalLayout->addWidget(line_salaire);

        combo_type = new QComboBox(layoutWidget);
        combo_type->setObjectName(QStringLiteral("combo_type"));

        verticalLayout->addWidget(combo_type);


        horizontalLayout_2->addLayout(verticalLayout);


        verticalLayout_6->addLayout(horizontalLayout_2);

        horizontalLayout_4 = new QHBoxLayout();
        horizontalLayout_4->setObjectName(QStringLiteral("horizontalLayout_4"));
        btn_ajout = new QPushButton(layoutWidget);
        btn_ajout->setObjectName(QStringLiteral("btn_ajout"));

        horizontalLayout_4->addWidget(btn_ajout);

        btn_modif = new QPushButton(layoutWidget);
        btn_modif->setObjectName(QStringLiteral("btn_modif"));

        horizontalLayout_4->addWidget(btn_modif);

        btn_sup = new QPushButton(layoutWidget);
        btn_sup->setObjectName(QStringLiteral("btn_sup"));

        horizontalLayout_4->addWidget(btn_sup);


        verticalLayout_6->addLayout(horizontalLayout_4);

        groupBox_2 = new QGroupBox(tab);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 270, 471, 171));
        groupBox_2->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        groupBox_2->setFlat(false);
        groupBox_2->setCheckable(false);
        layoutWidget1 = new QWidget(groupBox_2);
        layoutWidget1->setObjectName(QStringLiteral("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(20, 40, 441, 111));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget1);
        horizontalLayout_3->setObjectName(QStringLiteral("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        verticalLayout_3 = new QVBoxLayout();
        verticalLayout_3->setObjectName(QStringLiteral("verticalLayout_3"));
        tout_afficher_emp = new QPushButton(layoutWidget1);
        tout_afficher_emp->setObjectName(QStringLiteral("tout_afficher_emp"));

        verticalLayout_3->addWidget(tout_afficher_emp);

        pdf_emp = new QPushButton(layoutWidget1);
        pdf_emp->setObjectName(QStringLiteral("pdf_emp"));

        verticalLayout_3->addWidget(pdf_emp);


        horizontalLayout_3->addLayout(verticalLayout_3);

        verticalLayout_5 = new QVBoxLayout();
        verticalLayout_5->setObjectName(QStringLiteral("verticalLayout_5"));
        verticalLayout_4 = new QVBoxLayout();
        verticalLayout_4->setObjectName(QStringLiteral("verticalLayout_4"));
        tri_salaire_emp = new QRadioButton(layoutWidget1);
        tri_salaire_emp->setObjectName(QStringLiteral("tri_salaire_emp"));

        verticalLayout_4->addWidget(tri_salaire_emp);

        tri_type_emp = new QRadioButton(layoutWidget1);
        tri_type_emp->setObjectName(QStringLiteral("tri_type_emp"));

        verticalLayout_4->addWidget(tri_type_emp);

        tri_nom_emp = new QRadioButton(layoutWidget1);
        tri_nom_emp->setObjectName(QStringLiteral("tri_nom_emp"));

        verticalLayout_4->addWidget(tri_nom_emp);


        verticalLayout_5->addLayout(verticalLayout_4);


        horizontalLayout_3->addLayout(verticalLayout_5);

        quitter_emp = new QPushButton(tab);
        quitter_emp->setObjectName(QStringLiteral("quitter_emp"));
        quitter_emp->setGeometry(QRect(790, 20, 111, 51));
        btn_chat_emp = new QPushButton(tab);
        btn_chat_emp->setObjectName(QStringLiteral("btn_chat_emp"));
        btn_chat_emp->setGeometry(QRect(670, 20, 101, 51));
        layoutWidget2 = new QWidget(tab);
        layoutWidget2->setObjectName(QStringLiteral("layoutWidget2"));
        layoutWidget2->setGeometry(QRect(20, 20, 471, 241));
        verticalLayout_7 = new QVBoxLayout(layoutWidget2);
        verticalLayout_7->setObjectName(QStringLiteral("verticalLayout_7"));
        verticalLayout_7->setContentsMargins(0, 0, 0, 0);
        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        label_8 = new QLabel(layoutWidget2);
        label_8->setObjectName(QStringLiteral("label_8"));

        horizontalLayout->addWidget(label_8);

        line_rech_emp = new QLineEdit(layoutWidget2);
        line_rech_emp->setObjectName(QStringLiteral("line_rech_emp"));

        horizontalLayout->addWidget(line_rech_emp);


        verticalLayout_7->addLayout(horizontalLayout);

        tableView = new QTableView(layoutWidget2);
        tableView->setObjectName(QStringLiteral("tableView"));

        verticalLayout_7->addWidget(tableView);

        layoutWidget3 = new QWidget(tab);
        layoutWidget3->setObjectName(QStringLiteral("layoutWidget3"));
        layoutWidget3->setGeometry(QRect(500, 80, 252, 58));
        verticalLayout_8 = new QVBoxLayout(layoutWidget3);
        verticalLayout_8->setObjectName(QStringLiteral("verticalLayout_8"));
        verticalLayout_8->setContentsMargins(0, 0, 0, 0);
        horizontalLayout_5 = new QHBoxLayout();
        horizontalLayout_5->setObjectName(QStringLiteral("horizontalLayout_5"));
        label_6 = new QLabel(layoutWidget3);
        label_6->setObjectName(QStringLiteral("label_6"));

        horizontalLayout_5->addWidget(label_6);

        comboBox_modif = new QComboBox(layoutWidget3);
        comboBox_modif->setObjectName(QStringLiteral("comboBox_modif"));

        horizontalLayout_5->addWidget(comboBox_modif);


        verticalLayout_8->addLayout(horizontalLayout_5);

        horizontalLayout_6 = new QHBoxLayout();
        horizontalLayout_6->setObjectName(QStringLiteral("horizontalLayout_6"));
        label_7 = new QLabel(layoutWidget3);
        label_7->setObjectName(QStringLiteral("label_7"));

        horizontalLayout_6->addWidget(label_7);

        comboBox_rech_emp = new QComboBox(layoutWidget3);
        comboBox_rech_emp->setObjectName(QStringLiteral("comboBox_rech_emp"));

        horizontalLayout_6->addWidget(comboBox_rech_emp);


        verticalLayout_8->addLayout(horizontalLayout_6);

        label_info = new QLabel(tab);
        label_info->setObjectName(QStringLiteral("label_info"));
        label_info->setGeometry(QRect(20, 460, 891, 20));
        tab_produits_2->addTab(tab, QString());
        tab_produits = new QWidget();
        tab_produits->setObjectName(QStringLiteral("tab_produits"));
        tab_produits_2->addTab(tab_produits, QString());
        tab_articles = new QWidget();
        tab_articles->setObjectName(QStringLiteral("tab_articles"));
        tab_produits_2->addTab(tab_articles, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tab_produits_2->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tab_produits_2->addTab(tab_3, QString());

        retranslateUi(Employee);

        tab_produits_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Employee);
    } // setupUi

    void retranslateUi(QWidget *Employee)
    {
        Employee->setWindowTitle(QApplication::translate("Employee", "Dialog", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("Employee", "Les informations de l'employe", Q_NULLPTR));
        label->setText(QApplication::translate("Employee", "ID", Q_NULLPTR));
        label_3->setText(QApplication::translate("Employee", "Nom", Q_NULLPTR));
        label_2->setText(QApplication::translate("Employee", "Prenom", Q_NULLPTR));
        label_4->setText(QApplication::translate("Employee", "Salaire", Q_NULLPTR));
        label_5->setText(QApplication::translate("Employee", "Type", Q_NULLPTR));
        combo_type->clear();
        combo_type->insertItems(0, QStringList()
         << QApplication::translate("Employee", "Employe", Q_NULLPTR)
         << QApplication::translate("Employee", "Manager", Q_NULLPTR)
         << QApplication::translate("Employee", "Receptionniste", Q_NULLPTR)
        );
        btn_ajout->setText(QApplication::translate("Employee", "AJOUTER", Q_NULLPTR));
        btn_modif->setText(QApplication::translate("Employee", "MODIFIER", Q_NULLPTR));
        btn_sup->setText(QApplication::translate("Employee", "SUPPRIMER", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("Employee", "Trier par:", Q_NULLPTR));
        tout_afficher_emp->setText(QApplication::translate("Employee", "TOUT AFFICHER", Q_NULLPTR));
        pdf_emp->setText(QApplication::translate("Employee", "PDF", Q_NULLPTR));
        tri_salaire_emp->setText(QApplication::translate("Employee", "Salaire", Q_NULLPTR));
        tri_type_emp->setText(QApplication::translate("Employee", "type", Q_NULLPTR));
        tri_nom_emp->setText(QApplication::translate("Employee", "Nom", Q_NULLPTR));
        quitter_emp->setText(QApplication::translate("Employee", "QUITTER", Q_NULLPTR));
        btn_chat_emp->setText(QApplication::translate("Employee", "CHAT", Q_NULLPTR));
        label_8->setText(QApplication::translate("Employee", "Recherche:", Q_NULLPTR));
        label_6->setText(QApplication::translate("Employee", "ID:", Q_NULLPTR));
        label_7->setText(QApplication::translate("Employee", "type de recherche:", Q_NULLPTR));
        comboBox_rech_emp->clear();
        comboBox_rech_emp->insertItems(0, QStringList()
         << QApplication::translate("Employee", "salaire ou id", Q_NULLPTR)
         << QApplication::translate("Employee", "type", Q_NULLPTR)
         << QApplication::translate("Employee", "nom", Q_NULLPTR)
        );
        label_info->setText(QString());
        tab_produits_2->setTabText(tab_produits_2->indexOf(tab), QApplication::translate("Employee", "GEmployee", Q_NULLPTR));
        tab_produits_2->setTabText(tab_produits_2->indexOf(tab_produits), QApplication::translate("Employee", "GProduits", Q_NULLPTR));
        tab_produits_2->setTabText(tab_produits_2->indexOf(tab_articles), QApplication::translate("Employee", "Garticles", Q_NULLPTR));
        tab_produits_2->setTabText(tab_produits_2->indexOf(tab_2), QApplication::translate("Employee", "Gmateriels", Q_NULLPTR));
        tab_produits_2->setTabText(tab_produits_2->indexOf(tab_3), QApplication::translate("Employee", "Gclients", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Employee: public Ui_Employee {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EMPLOYEE_H
